name: Build and Release Executable

on:
  push:
    tags:
      - 'v*' # タグが "v" で始まる場合にトリガー

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet publish -c Release -r win-x64 --self-contained true -o ./publish

    - name: Archive the build
      run: zip -r SlideTitleExtractor.zip ./publish

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: SlideTitleExtractor.zip
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        tag: ${{ github.ref_name }}
        name: "Release ${{ github.ref_name }}"
        body: |
          ### What's New
          - This release includes the latest build of SlideTitleExtractor.
        draft: false
        prerelease: false
